// inquiries.ts

export type Inquiry = {
  id: number;
  venue: string;
  contactPerson: string;
  email: string;
  eventDate: string;
  deadline: string;
  eventType: 'Party' | 'Wedding' | 'Conference' | 'Other';
  guests: number;
  notes: boolean;
  status: 'PENDING' | 'ACCEPTED' | 'REJECTED' | 'QUOTED';
};

export const inquiries: Inquiry[] = [
  {
    id: 1,
    venue: 'Diamond Hall',
    contactPerson: 'Noah Carter',
    email: 'noah.carter@example.com',
    eventDate: '10 days ago',
    deadline: '5 days ago',
    eventType: 'Wedding',
    guests: 450,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 2,
    venue: 'Lakeside Pavilion',
    contactPerson: 'Ella Rivera',
    email: 'ella.rivera@example.com',
    eventDate: '3 days ago',
    deadline: 'In 4 days',
    eventType: 'Conference',
    guests: 600,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 3,
    venue: 'The Royal Court',
    contactPerson: 'Jacob Adams',
    email: 'jacob.adams@example.com',
    eventDate: '8 days ago',
    deadline: 'Tomorrow',
    eventType: 'Party',
    guests: 300,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 4,
    venue: 'Harmony Gardens',
    contactPerson: 'Avery Scott',
    email: 'avery.scott@example.com',
    eventDate: '12 days ago',
    deadline: 'Yesterday',
    eventType: 'Other',
    guests: 75,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 5,
    venue: 'Golden Orchid Hall',
    contactPerson: 'Mason Turner',
    email: 'mason.turner@example.com',
    eventDate: '20 days ago',
    deadline: '6 days ago',
    eventType: 'Wedding',
    guests: 520,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 6,
    venue: 'Evergreen Plaza',
    contactPerson: 'Sophia White',
    email: 'sophia.white@example.com',
    eventDate: 'Yesterday',
    deadline: 'In 2 days',
    eventType: 'Party',
    guests: 180,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 7,
    venue: 'Ocean Pearl Resort',
    contactPerson: 'James Bennett',
    email: 'james.bennett@example.com',
    eventDate: '14 days ago',
    deadline: '5 days ago',
    eventType: 'Conference',
    guests: 1100,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 8,
    venue: 'Sunrise Hall',
    contactPerson: 'Chloe Foster',
    email: 'chloe.foster@example.com',
    eventDate: '6 days ago',
    deadline: 'Today',
    eventType: 'Wedding',
    guests: 340,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 9,
    venue: 'Crystal Lake Venue',
    contactPerson: 'Daniel Hughes',
    email: 'daniel.hughes@example.com',
    eventDate: '18 days ago',
    deadline: 'In 3 days',
    eventType: 'Party',
    guests: 220,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 10,
    venue: 'Grand Horizon Center',
    contactPerson: 'Lily Ramirez',
    email: 'lily.ramirez@example.com',
    eventDate: '2 days ago',
    deadline: 'Tomorrow',
    eventType: 'Conference',
    guests: 950,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 11,
    venue: 'Maplewood Hall',
    contactPerson: 'Ethan Brooks',
    email: 'ethan.brooks@example.com',
    eventDate: '7 days ago',
    deadline: 'Today',
    eventType: 'Wedding',
    guests: 410,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 12,
    venue: 'Azure Banquet',
    contactPerson: 'Harper Collins',
    email: 'harper.collins@example.com',
    eventDate: '25 days ago',
    deadline: '3 days ago',
    eventType: 'Other',
    guests: 95,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 13,
    venue: 'Rosewood Pavilion',
    contactPerson: 'Alexander Reed',
    email: 'alex.reed@example.com',
    eventDate: '4 days ago',
    deadline: 'Tomorrow',
    eventType: 'Party',
    guests: 280,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 14,
    venue: 'The Imperial Center',
    contactPerson: 'Grace Cooper',
    email: 'grace.cooper@example.com',
    eventDate: '9 days ago',
    deadline: 'Yesterday',
    eventType: 'Conference',
    guests: 1200,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 15,
    venue: 'Emerald Palace',
    contactPerson: 'Logan Phillips',
    email: 'logan.phillips@example.com',
    eventDate: '16 days ago',
    deadline: 'In 2 days',
    eventType: 'Wedding',
    guests: 530,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 16,
    venue: 'Silverstone Hall',
    contactPerson: 'Amelia Evans',
    email: 'amelia.evans@example.com',
    eventDate: '11 days ago',
    deadline: '5 days ago',
    eventType: 'Party',
    guests: 160,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 17,
    venue: 'Blue Sky Convention',
    contactPerson: 'Sebastian Diaz',
    email: 'sebastian.diaz@example.com',
    eventDate: '22 days ago',
    deadline: '6 days ago',
    eventType: 'Conference',
    guests: 1350,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 18,
    venue: 'Golden Gate Hall',
    contactPerson: 'Victoria Lopez',
    email: 'victoria.lopez@example.com',
    eventDate: '5 days ago',
    deadline: 'Today',
    eventType: 'Other',
    guests: 65,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 19,
    venue: 'Majestic Gardens',
    contactPerson: 'Lucas Scott',
    email: 'lucas.scott@example.com',
    eventDate: '13 days ago',
    deadline: 'Yesterday',
    eventType: 'Wedding',
    guests: 480,
    notes: true,
    status: 'PENDING',
  },
  {
    id: 20,
    venue: 'Coral Reef Club',
    contactPerson: 'Isabella Walker',
    email: 'isabella.walker@example.com',
    eventDate: '1 day ago',
    deadline: 'Tomorrow',
    eventType: 'Party',
    guests: 310,
    notes: true,
    status: 'PENDING',
  },

  // --- keep going until id: 65 ---
  ...Array.from({ length: 45 }, (_, i) => ({
    id: i + 21,
    venue: `Venue ${i + 21}`,
    contactPerson: `Person ${i + 21}`,
    email: `person${i + 21}@example.com`,
    eventDate: `${(i % 40) + 1} days ago`,
    deadline: `${(i % 15) + 1} days ago`,
    eventType: (['Party', 'Wedding', 'Conference', 'Other'] as const)[i % 4],
    guests: (i + 1) * 10,
    notes: i % 2 === 0,
    status: (['PENDING', 'ACCEPTED', 'REJECTED', 'QUOTED'] as const)[i % 4],
  })),
];