
export type Location = {
  id: string;
  image_url: string;
  map_link: string | null;
  name: string;
  inquiries: string | number;
  reservations: number;
  overall_score: number;
  status: "Active" | "Inactive" | "Pending";
  min_capacity: number;
  max_capacity: number;
  address: string;
  primary_phone: string;
  secondary_phone: string;
  attributes: ("bed" | "check" | "car" | "mail")[];
  event_types: string[];
};

export const locations: Location[] = [
  {
    id: "1",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Mr. Lucio Feeney",
    inquiries: 5,
    reservations: 2,
    overall_score: 8,
    status: "Active",
    min_capacity: 50,
    max_capacity: 300,
    address: "14938 Ella Ways Suite 323 Carlieview, MO 32821-8325",
    primary_phone: "+1-202-555-1101",
    secondary_phone: "+1-303-555-2101",
    attributes: ["bed", "check", "car", "mail"],
    event_types: ["Wedding", "Birthday"],
  },
  {
    id: "2",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Prof. Kathleen Strosin IV",
    inquiries: 10,
    reservations: 4,
    overall_score: 6,
    status: "Active",
    min_capacity: 30,
    max_capacity: 200,
    address: "7420 Harbor Lane Apt. 204 Brookhaven, TX 75062-1143",
    primary_phone: "+1-202-555-1102",
    secondary_phone: "+1-303-555-2102",
    attributes: ["bed", "check", "car"],
    event_types: ["Corporate", "Birthday"],
  },
  {
    id: "3",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Brenda Heller DVM",
    inquiries: 3,
    reservations: 1,
    overall_score: 9,
    status: "Active",
    min_capacity: 40,
    max_capacity: 250,
    address: "9831 Willow Drive Suite 112 Fairmont, CA 90210-3375",
    primary_phone: "+1-202-555-1103",
    secondary_phone: "+1-303-555-2103",
    attributes: ["bed", "check", "car", "mail"],
    event_types: ["Party", "Concert"],
  },
  {
    id: "4",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Dr. Victor Emard",
    inquiries: 7,
    reservations: 3,
    overall_score: 5,
    status: "Active",
    min_capacity: 60,
    max_capacity: 400,
    address: "562 Orchard Street Apt. 45 Greenwood, NY 11743-5562",
    primary_phone: "+1-202-555-1104",
    secondary_phone: "+1-303-555-2104",
    attributes: ["check", "car"],
    event_types: ["Meeting", "Wedding"],
  },
  {
    id: "5",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Jeramie Schimmel",
    inquiries: 2,
    reservations: 0,
    overall_score: 7,
    status: "Active",
    min_capacity: 20,
    max_capacity: 150,
    address: "10477 Pine Hills Road Suite 12 Crestwood, FL 33176-2389",
    primary_phone: "+1-202-555-1105",
    secondary_phone: "+1-303-555-2105",
    attributes: ["mail","bed"],
    event_types: ["Birthday"],
  },
  {
    id: "6",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Jennyfer Stoltenberg DDS",
    inquiries: "N/A",
    reservations: 6,
    overall_score: 8,
    status: "Active",
    min_capacity: 70,
    max_capacity: 350,
    address: "2930 Meadowbrook Blvd Apt. 67 Oakridge, IL 60614-9821",
    primary_phone: "+1-202-555-1106",
    secondary_phone: "+1-303-555-2106",
    attributes: ["bed", "mail"],
    event_types: ["Meeting", "Birthday"],
  },
  {
    id: "7",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Prof. Cade Kertzmann Sr.",
    inquiries: 8,
    reservations: 5,
    overall_score: 6,
    status: "Active",
    min_capacity: 90,
    max_capacity: 280,
    address: "8712 Grandview Terrace Suite 509 Maplewood, NJ 07052-7110",
    primary_phone: "+1-202-555-1107",
    secondary_phone: "+1-303-555-2107",
    attributes: ["check", "car", "mail"],
    event_types: ["Wedding", "Party"],
  },
  {
    id: "8",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Clarabelle Purdy",
    inquiries: 4,
    reservations: 1,
    overall_score: 5,
    status: "Active",
    min_capacity: 40,
    max_capacity: 220,
    address: "4527 Lakewood Avenue Apt. 78 Ridgefield, WA 98642-1233",
    primary_phone: "+1-202-555-1108",
    secondary_phone: "+1-303-555-2108",
    attributes: ["mail", "car"],
    event_types: ["Birthday"],
  },
  {
    id: "9",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Prof. Dejon Hickle I",
    inquiries: 6,
    reservations: 2,
    overall_score: 9,
    status: "Active",
    min_capacity: 80,
    max_capacity: 450,
    address: "6639 Sunset Blvd Suite 214 Silverlake, CA 90026-8421",
    primary_phone: "+1-202-555-1109",
    secondary_phone: "+1-303-555-2109",
    attributes: ["bed", "check"],
    event_types: ["Party", "Wedding"],
  },
  {
    id: "10",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Caesar Nikolaus V",
    inquiries: "N/A",
    reservations: 7,
    overall_score: 7,
    status: "Active",
    min_capacity: 100,
    max_capacity: 500,
    address: "3981 Highland Park Suite 98 Denver, CO 80210-4432",
    primary_phone: "+1-202-555-1110",
    secondary_phone: "+1-303-555-2110",
    attributes: ["car"],
    event_types: ["Birthday"],
  },
  {
    id: "11",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Edward Hegmann PhD",
    inquiries: 9,
    reservations: 3,
    overall_score: 8,
    status: "Active",
    min_capacity: 55,
    max_capacity: 270,
    address: "7514 Oakdale Street Apt. 312 Franklin, TN 37064-1132",
    primary_phone: "+1-202-555-1111",
    secondary_phone: "+1-303-555-2111",
    attributes: ["mail"],
    event_types: ["Birthday", "Party"],
  },
  {
    id: "12",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Bernardo Jenkins MD",
    inquiries: 13,
    reservations: 8,
    overall_score: 9,
    status: "Active",
    min_capacity: 75,
    max_capacity: 420,
    address: "5723 Aspen Court Suite 407 Greenwood, IN 46142-9820",
    primary_phone: "+1-202-555-1112",
    secondary_phone: "+1-303-555-2112",
    attributes: ["bed", "check", "car"],
    event_types: ["Wedding", "Party"],
  },
  {
    id: "13",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Stefanie Hansen",
    inquiries: 7,
    reservations: 2,
    overall_score: 5,
    status: "Active",
    min_capacity: 45,
    max_capacity: 210,
    address: "6849 Birchwood Lane Apt. 14 Hamilton, OH 45011-2741",
    primary_phone: "+1-202-555-1113",
    secondary_phone: "+1-303-555-2113",
    attributes: ["car"],
    event_types: ["Birthday"],
  },
  {
    id: "14",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Marco Blick",
    inquiries: "N/A",
    reservations: 0,
    overall_score: 6,
    status: "Active",
    min_capacity: 25,
    max_capacity: 160,
    address: "2197 Maple Grove Ave Suite 18 Charleston, SC 29407-1239",
    primary_phone: "+1-202-555-1114",
    secondary_phone: "+1-303-555-2114",
    attributes: ["mail", "bed"],
    event_types: ["Wedding"],
  },
  {
    id: "15",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Cristopher Lehner III",
    inquiries: 14,
    reservations: 9,
    overall_score: 10,
    status: "Active",
    min_capacity: 95,
    max_capacity: 480,
    address: "9246 Brookstone Blvd Apt. 67 Austin, TX 73301-5629",
    primary_phone: "+1-202-555-1115",
    secondary_phone: "+1-303-555-2115",
    attributes: ["check"],
    event_types: ["Party", "Meeting"],
  },
  {
    id: "16",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Keara Monahan",
    inquiries: 6,
    reservations: 4,
    overall_score: 7,
    status: "Active",
    min_capacity: 65,
    max_capacity: 320,
    address: "4738 Sycamore Street Suite 310 Rochester, MN 55901-9082",
    primary_phone: "+1-202-555-1116",
    secondary_phone: "+1-303-555-2116",
    attributes: ["car", "bed", "check", "mail"],
    event_types: ["Meeting"],
  },
  {
    id: "17",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Dr. Uriel Altenwerth",
    inquiries: 5,
    reservations: 2,
    overall_score: 8,
    status: "Active",
    min_capacity: 50,
    max_capacity: 300,
    address: "8302 Redwood Ave Apt. 22 Bellevue, WA 98005-4441",
    primary_phone: "+1-202-555-1117",
    secondary_phone: "+1-303-555-2117",
    attributes: ["mail"],
    event_types: ["Meeting", "Party"],
  },
  {
    id: "18",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Pink Bode",
    inquiries: 3,
    reservations: 1,
    overall_score: 4,
    status: "Active",
    min_capacity: 40,
    max_capacity: 200,
    address: "5931 Valley Road Suite 114 Portland, OR 97219-7754",
    primary_phone: "+1-202-555-1118",
    secondary_phone: "+1-303-555-2118",
    attributes: ["check"],
    event_types: ["Birthday", "Party"],
  },
  {
    id: "19",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Morton O'Hara",
    inquiries: "N/A",
    reservations: 5,
    overall_score: 7,
    status: "Active",
    min_capacity: 70,
    max_capacity: 360,
    address: "4028 Cypress Drive Apt. 55 Tampa, FL 33617-4471",
    primary_phone: "+1-202-555-1119",
    secondary_phone: "+1-303-555-2119",
    attributes: ["car"],
    event_types: ["Concert"],
  },
  {
    id: "20",
    image_url: "/venue-dummy.png",
    map_link: null,
    name: "Dawson Bradtke",
    inquiries: "N/A",
    reservations: 4,
    overall_score: 9,
    status: "Active",
    min_capacity: 85,
    max_capacity: 410,
    address: "1185 Aspen Hill Rd Suite 220 Springfield, VA 22150-6543",
    primary_phone: "+1-202-555-1120",
    secondary_phone: "+1-303-555-2120",
    attributes: ["bed", "check"],
    event_types: ["Wedding", "Party"],
  },
];
