import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import Navbar from "@/components/Navbar";
import { AppSidebar } from "@/components/AppSidebar";
import { cookies } from "next/headers";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
     const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"
  return (
    <html lang="en">
      <body
        className={`ProvistSans.variable} ${geistMono.variable} antialiased flex`}
        suppressHydrationWarning
      >
        <SidebarProvider defaultOpen={defaultOpen}>
          <AppSidebar />
         <main className="w-full ">
           <Navbar />
          <div className="p-2">
            {children}
          </div>
         </main>
        </SidebarProvider>
      </body>
    </html>
  );
}